package paoo.game.tile;

import paoo.game.panel.GamePanel;

import javax.imageio.ImageIO;
import java.awt.*;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.Objects;

// Flyweight pattern
public class TileManager {
    private GamePanel gamePanel;
    private Tile[] tiles;

    private int[][] mapTileNumber;

    public TileManager(GamePanel gamePanel) {
        this.gamePanel = gamePanel;
        tiles = new Tile[3336]; // Array of different tiles type
        mapTileNumber = new int[gamePanel.getMAX_WORLD_COLUMN()][gamePanel.getMAX_WORLD_ROW()];

        getTileImage();
        loadMap("/maps/mapa.txt");
    }

    public void getTileImage() {
        try {

            tiles[0] = new Tile();
            tiles[0].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_0.png")));
            tiles[1] = new Tile();
            tiles[1].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1.png")));
            tiles[2] = new Tile();
            tiles[2].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2.png")));
            tiles[85] = new Tile();
            tiles[85].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_85.png")));
            tiles[86] = new Tile();
            tiles[86].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_86.png")));
            tiles[87] = new Tile();
            tiles[87].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_87.png")));
            tiles[170] = new Tile();
            tiles[170].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_170.png")));
            tiles[171] = new Tile();
            tiles[171].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_171.png")));
            tiles[172] = new Tile();
            tiles[172].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_172.png")));
            tiles[481] = new Tile();
            tiles[481].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_481.png")));
            tiles[482] = new Tile();
            tiles[482].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_482.png")));
            tiles[483] = new Tile();
            tiles[483].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_483.png")));
            tiles[484] = new Tile();
            tiles[484].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_484.png")));
            tiles[485] = new Tile();
            tiles[485].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_485.png")));
            tiles[486] = new Tile();
            tiles[486].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_486.png")));
            tiles[487] = new Tile();
            tiles[487].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_487.png")));
            tiles[488] = new Tile();
            tiles[488].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_488.png")));
            tiles[566] = new Tile();
            tiles[566].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_566.png")));
            tiles[567] = new Tile();
            tiles[567].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_567.png")));
            tiles[568] = new Tile();
            tiles[568].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_568.png")));
            tiles[569] = new Tile();
            tiles[569].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_569.png")));
            tiles[570] = new Tile();
            tiles[570].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_570.png")));
            tiles[571] = new Tile();
            tiles[571].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_571.png")));
            tiles[572] = new Tile();
            tiles[572].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_572.png")));
            tiles[573] = new Tile();
            tiles[573].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_573.png")));
            tiles[651] = new Tile();
            tiles[651].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_651.png")));
            tiles[652] = new Tile();
            tiles[652].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_652.png")));
            tiles[653] = new Tile();
            tiles[653].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_653.png")));
            tiles[654] = new Tile();
            tiles[654].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_654.png")));
            tiles[655] = new Tile();
            tiles[655].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_655.png")));
            tiles[656] = new Tile();
            tiles[656].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_656.png")));
            tiles[657] = new Tile();
            tiles[657].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_657.png")));
            tiles[658] = new Tile();
            tiles[658].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_658.png")));
            tiles[736] = new Tile();
            tiles[736].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_736.png")));
            tiles[737] = new Tile();
            tiles[737].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_737.png")));
            tiles[738] = new Tile();
            tiles[738].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_738.png")));
            tiles[739] = new Tile();
            tiles[739].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_739.png")));
            tiles[740] = new Tile();
            tiles[740].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_740.png")));
            tiles[741] = new Tile();
            tiles[741].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_741.png")));
            tiles[742] = new Tile();
            tiles[742].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_742.png")));
            tiles[743] = new Tile();
            tiles[743].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_743.png")));
            tiles[821] = new Tile();
            tiles[821].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_821.png")));
            tiles[822] = new Tile();
            tiles[822].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_822.png")));
            tiles[823] = new Tile();
            tiles[823].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_823.png")));
            tiles[824] = new Tile();
            tiles[824].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_824.png")));
            tiles[825] = new Tile();
            tiles[825].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_825.png")));
            tiles[826] = new Tile();
            tiles[826].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_826.png")));
            tiles[827] = new Tile();
            tiles[827].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_827.png")));
            tiles[828] = new Tile();
            tiles[828].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_828.png")));
            tiles[906] = new Tile();
            tiles[906].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_906.png")));
            tiles[907] = new Tile();
            tiles[907].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_907.png")));
            tiles[908] = new Tile();
            tiles[908].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_908.png")));
            tiles[909] = new Tile();
            tiles[909].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_909.png")));
            tiles[910] = new Tile();
            tiles[910].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_910.png")));
            tiles[911] = new Tile();
            tiles[911].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_911.png")));
            tiles[912] = new Tile();
            tiles[912].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_912.png")));
            tiles[913] = new Tile();
            tiles[913].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_913.png")));
            tiles[918] = new Tile();
            tiles[918].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_918.png")));
            tiles[919] = new Tile();
            tiles[919].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_919.png")));
            tiles[991] = new Tile();
            tiles[991].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_991.png")));
            tiles[992] = new Tile();
            tiles[992].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_992.png")));
            tiles[993] = new Tile();
            tiles[993].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_993.png")));
            tiles[994] = new Tile();
            tiles[994].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_994.png")));
            tiles[995] = new Tile();
            tiles[995].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_995.png")));
            tiles[996] = new Tile();
            tiles[996].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_996.png")));
            tiles[997] = new Tile();
            tiles[997].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_997.png")));
            tiles[1003] = new Tile();
            tiles[1003].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1003.png")));
            tiles[1004] = new Tile();
            tiles[1004].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1004.png")));
            tiles[1037] = new Tile();
            tiles[1037].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1037.png")));
            tiles[1076] = new Tile();
            tiles[1076].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1076.png")));
            tiles[1077] = new Tile();
            tiles[1077].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1077.png")));
            tiles[1078] = new Tile();
            tiles[1078].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1078.png")));
            tiles[1079] = new Tile();
            tiles[1079].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1079.png")));
            tiles[1080] = new Tile();
            tiles[1080].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1080.png")));
            tiles[1081] = new Tile();
            tiles[1081].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1081.png")));
            tiles[1082] = new Tile();
            tiles[1082].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1082.png")));
            tiles[1088] = new Tile();
            tiles[1088].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1088.png")));
            tiles[1089] = new Tile();
            tiles[1089].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1089.png")));
            tiles[1144] = new Tile();
            tiles[1144].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1144.png")));
            tiles[1145] = new Tile();
            tiles[1145].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1145.png")));
            tiles[1146] = new Tile();
            tiles[1146].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1146.png")));
            tiles[1161] = new Tile();
            tiles[1161].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1161.png")));
            tiles[1162] = new Tile();
            tiles[1162].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1162.png")));
            tiles[1163] = new Tile();
            tiles[1163].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1163.png")));
            tiles[1164] = new Tile();
            tiles[1164].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1164.png")));
            tiles[1165] = new Tile();
            tiles[1165].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1165.png")));
            tiles[1166] = new Tile();
            tiles[1166].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1166.png")));
            tiles[1167] = new Tile();
            tiles[1167].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1167.png")));
            tiles[1173] = new Tile();
            tiles[1173].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1173.png")));
            tiles[1174] = new Tile();
            tiles[1174].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1174.png")));
            tiles[1227] = new Tile();
            tiles[1227].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1227.png")));
            tiles[1228] = new Tile();
            tiles[1228].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1228.png")));
            tiles[1229] = new Tile();
            tiles[1229].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1229.png")));
            tiles[1230] = new Tile();
            tiles[1230].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1230.png")));
            tiles[1231] = new Tile();
            tiles[1231].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1231.png")));
            tiles[1232] = new Tile();
            tiles[1232].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1232.png")));
            tiles[1233] = new Tile();
            tiles[1233].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1233.png")));
            tiles[1310] = new Tile();
            tiles[1310].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1310.png")));
            tiles[1311] = new Tile();
            tiles[1311].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1311.png")));
            tiles[1312] = new Tile();
            tiles[1312].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1312.png")));
            tiles[1313] = new Tile();
            tiles[1313].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1313.png")));
            tiles[1314] = new Tile();
            tiles[1314].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1314.png")));
            tiles[1315] = new Tile();
            tiles[1315].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1315.png")));
            tiles[1316] = new Tile();
            tiles[1316].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1316.png")));
            tiles[1317] = new Tile();
            tiles[1317].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1317.png")));
            tiles[1318] = new Tile();
            tiles[1318].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1318.png")));
            tiles[1319] = new Tile();
            tiles[1319].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1319.png")));
            tiles[1320] = new Tile();
            tiles[1320].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1320.png")));
            tiles[1370] = new Tile();
            tiles[1370].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1370.png")));
            tiles[1455] = new Tile();
            tiles[1455].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1455.png")));
            tiles[1484] = new Tile();
            tiles[1484].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1484.png")));
            tiles[1485] = new Tile();
            tiles[1485].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1485.png")));
            tiles[1486] = new Tile();
            tiles[1486].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1486.png")));
            tiles[1542] = new Tile();
            tiles[1542].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1542.png")));
            tiles[1543] = new Tile();
            tiles[1543].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1543.png")));
            tiles[1544] = new Tile();
            tiles[1544].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1544.png")));
            tiles[1565] = new Tile();
            tiles[1565].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1565.png")));
            tiles[1567] = new Tile();
            tiles[1567].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1567.png")));
            tiles[1568] = new Tile();
            tiles[1568].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1568.png")));
            tiles[1569] = new Tile();
            tiles[1569].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1569.png")));
            tiles[1570] = new Tile();
            tiles[1570].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1570.png")));
            tiles[1571] = new Tile();
            tiles[1571].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1571.png")));
            tiles[1572] = new Tile();
            tiles[1572].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1572.png")));
            tiles[1573] = new Tile();
            tiles[1573].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1573.png")));
            tiles[1575] = new Tile();
            tiles[1575].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1575.png")));
            tiles[1627] = new Tile();
            tiles[1627].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1627.png")));
            tiles[1628] = new Tile();
            tiles[1628].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1628.png")));
            tiles[1650] = new Tile();
            tiles[1650].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1650.png")));
            tiles[1651] = new Tile();
            tiles[1651].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1651.png")));
            tiles[1652] = new Tile();
            tiles[1652].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1652.png")));
            tiles[1658] = new Tile();
            tiles[1658].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1658.png")));
            tiles[1659] = new Tile();
            tiles[1659].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1659.png")));
            tiles[1660] = new Tile();
            tiles[1660].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1660.png")));
            tiles[1712] = new Tile();
            tiles[1712].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1712.png")));
            tiles[1745] = new Tile();
            tiles[1745].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1745.png")));
            tiles[1822] = new Tile();
            tiles[1822].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1822.png")));
            tiles[1830] = new Tile();
            tiles[1830].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1830.png")));
            tiles[1885] = new Tile();
            tiles[1885].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1885.png")));
            tiles[1905] = new Tile();
            tiles[1905].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1905.png")));
            tiles[1910] = new Tile();
            tiles[1910].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1910.png")));
            tiles[1915] = new Tile();
            tiles[1915].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1915.png")));
            tiles[1975] = new Tile();
            tiles[1975].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1975.png")));
            tiles[1990] = new Tile();
            tiles[1990].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1990.png")));
            tiles[1995] = new Tile();
            tiles[1995].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_1995.png")));
            tiles[2000] = new Tile();
            tiles[2000].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2000.png")));
            tiles[2051] = new Tile();
            tiles[2051].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2051.png")));
            tiles[2075] = new Tile();
            tiles[2075].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2075.png")));
            tiles[2076] = new Tile();
            tiles[2076].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2076.png")));
            tiles[2079] = new Tile();
            tiles[2079].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2079.png")));
            tiles[2080] = new Tile();
            tiles[2080].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2080.png")));
            tiles[2085] = new Tile();
            tiles[2085].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2085.png")));
            tiles[2554] = new Tile();
            tiles[2554].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2554.png")));
            tiles[2555] = new Tile();
            tiles[2555].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2555.png")));
            tiles[2556] = new Tile();
            tiles[2556].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2556.png")));
            tiles[2557] = new Tile();
            tiles[2557].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2557.png")));
            tiles[2558] = new Tile();
            tiles[2558].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2558.png")));
            tiles[2559] = new Tile();
            tiles[2559].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2559.png")));
            tiles[2560] = new Tile();
            tiles[2560].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2560.png")));
            tiles[2561] = new Tile();
            tiles[2561].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2561.png")));
            tiles[2562] = new Tile();
            tiles[2562].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2562.png")));
            tiles[2563] = new Tile();
            tiles[2563].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2563.png")));
            tiles[2564] = new Tile();
            tiles[2564].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2564.png")));
            tiles[2565] = new Tile();
            tiles[2565].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2565.png")));
            tiles[2566] = new Tile();
            tiles[2566].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2566.png")));
            tiles[2567] = new Tile();
            tiles[2567].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2567.png")));
            tiles[2568] = new Tile();
            tiles[2568].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2568.png")));
            tiles[2569] = new Tile();
            tiles[2569].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2569.png")));
            tiles[2570] = new Tile();
            tiles[2570].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2570.png")));
            tiles[2618] = new Tile();
            tiles[2618].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2618.png")));
            tiles[2639] = new Tile();
            tiles[2639].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2639.png")));
            tiles[2640] = new Tile();
            tiles[2640].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2640.png")));
            tiles[2641] = new Tile();
            tiles[2641].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2641.png")));
            tiles[2642] = new Tile();
            tiles[2642].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2642.png")));
            tiles[2643] = new Tile();
            tiles[2643].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2643.png")));
            tiles[2644] = new Tile();
            tiles[2644].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2644.png")));
            tiles[2645] = new Tile();
            tiles[2645].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2645.png")));
            tiles[2646] = new Tile();
            tiles[2646].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2646.png")));
            tiles[2647] = new Tile();
            tiles[2647].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2647.png")));
            tiles[2648] = new Tile();
            tiles[2648].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2648.png")));
            tiles[2649] = new Tile();
            tiles[2649].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2649.png")));
            tiles[2650] = new Tile();
            tiles[2650].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2650.png")));
            tiles[2651] = new Tile();
            tiles[2651].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2651.png")));
            tiles[2652] = new Tile();
            tiles[2652].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2652.png")));
            tiles[2653] = new Tile();
            tiles[2653].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2653.png")));
            tiles[2654] = new Tile();
            tiles[2654].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2654.png")));
            tiles[2655] = new Tile();
            tiles[2655].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2655.png")));
            tiles[2724] = new Tile();
            tiles[2724].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2724.png")));
            tiles[2725] = new Tile();
            tiles[2725].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2725.png")));
            tiles[2726] = new Tile();
            tiles[2726].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2726.png")));
            tiles[2727] = new Tile();
            tiles[2727].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2727.png")));
            tiles[2728] = new Tile();
            tiles[2728].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2728.png")));
            tiles[2729] = new Tile();
            tiles[2729].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2729.png")));
            tiles[2730] = new Tile();
            tiles[2730].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2730.png")));
            tiles[2731] = new Tile();
            tiles[2731].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2731.png")));
            tiles[2732] = new Tile();
            tiles[2732].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2732.png")));
            tiles[2733] = new Tile();
            tiles[2733].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2733.png")));
            tiles[2734] = new Tile();
            tiles[2734].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2734.png")));
            tiles[2735] = new Tile();
            tiles[2735].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2735.png")));
            tiles[2736] = new Tile();
            tiles[2736].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2736.png")));
            tiles[2737] = new Tile();
            tiles[2737].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2737.png")));
            tiles[2738] = new Tile();
            tiles[2738].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2738.png")));
            tiles[2739] = new Tile();
            tiles[2739].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2739.png")));
            tiles[2740] = new Tile();
            tiles[2740].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2740.png")));
            tiles[2809] = new Tile();
            tiles[2809].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2809.png")));
            tiles[2810] = new Tile();
            tiles[2810].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2810.png")));
            tiles[2811] = new Tile();
            tiles[2811].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2811.png")));
            tiles[2812] = new Tile();
            tiles[2812].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2812.png")));
            tiles[2813] = new Tile();
            tiles[2813].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2813.png")));
            tiles[2814] = new Tile();
            tiles[2814].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2814.png")));
            tiles[2815] = new Tile();
            tiles[2815].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2815.png")));
            tiles[2816] = new Tile();
            tiles[2816].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2816.png")));
            tiles[2817] = new Tile();
            tiles[2817].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2817.png")));
            tiles[2818] = new Tile();
            tiles[2818].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2818.png")));
            tiles[2819] = new Tile();
            tiles[2819].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2819.png")));
            tiles[2820] = new Tile();
            tiles[2820].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2820.png")));
            tiles[2821] = new Tile();
            tiles[2821].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2821.png")));
            tiles[2822] = new Tile();
            tiles[2822].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2822.png")));
            tiles[2823] = new Tile();
            tiles[2823].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2823.png")));
            tiles[2824] = new Tile();
            tiles[2824].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2824.png")));
            tiles[2825] = new Tile();
            tiles[2825].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2825.png")));
            tiles[2894] = new Tile();
            tiles[2894].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2894.png")));
            tiles[2895] = new Tile();
            tiles[2895].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2895.png")));
            tiles[2896] = new Tile();
            tiles[2896].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2896.png")));
            tiles[2897] = new Tile();
            tiles[2897].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2897.png")));
            tiles[2898] = new Tile();
            tiles[2898].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2898.png")));
            tiles[2899] = new Tile();
            tiles[2899].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2899.png")));
            tiles[2900] = new Tile();
            tiles[2900].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2900.png")));
            tiles[2901] = new Tile();
            tiles[2901].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2901.png")));
            tiles[2902] = new Tile();
            tiles[2902].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2902.png")));
            tiles[2903] = new Tile();
            tiles[2903].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2903.png")));
            tiles[2904] = new Tile();
            tiles[2904].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2904.png")));
            tiles[2905] = new Tile();
            tiles[2905].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2905.png")));
            tiles[2906] = new Tile();
            tiles[2906].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2906.png")));
            tiles[2907] = new Tile();
            tiles[2907].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2907.png")));
            tiles[2908] = new Tile();
            tiles[2908].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2908.png")));
            tiles[2909] = new Tile();
            tiles[2909].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2909.png")));
            tiles[2910] = new Tile();
            tiles[2910].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2910.png")));
            tiles[2979] = new Tile();
            tiles[2979].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2979.png")));
            tiles[2980] = new Tile();
            tiles[2980].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2980.png")));
            tiles[2981] = new Tile();
            tiles[2981].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2981.png")));
            tiles[2982] = new Tile();
            tiles[2982].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2982.png")));
            tiles[2983] = new Tile();
            tiles[2983].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2983.png")));
            tiles[2984] = new Tile();
            tiles[2984].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2984.png")));
            tiles[2985] = new Tile();
            tiles[2985].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2985.png")));
            tiles[2986] = new Tile();
            tiles[2986].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2986.png")));
            tiles[2987] = new Tile();
            tiles[2987].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2987.png")));
            tiles[2988] = new Tile();
            tiles[2988].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2988.png")));
            tiles[2989] = new Tile();
            tiles[2989].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2989.png")));
            tiles[2990] = new Tile();
            tiles[2990].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2990.png")));
            tiles[2991] = new Tile();
            tiles[2991].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2991.png")));
            tiles[2992] = new Tile();
            tiles[2992].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2992.png")));
            tiles[2993] = new Tile();
            tiles[2993].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2993.png")));
            tiles[2994] = new Tile();
            tiles[2994].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2994.png")));
            tiles[2995] = new Tile();
            tiles[2995].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_2995.png")));
            tiles[3064] = new Tile();
            tiles[3064].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3064.png")));
            tiles[3065] = new Tile();
            tiles[3065].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3065.png")));
            tiles[3066] = new Tile();
            tiles[3066].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3066.png")));
            tiles[3067] = new Tile();
            tiles[3067].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3067.png")));
            tiles[3068] = new Tile();
            tiles[3068].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3068.png")));
            tiles[3069] = new Tile();
            tiles[3069].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3069.png")));
            tiles[3070] = new Tile();
            tiles[3070].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3070.png")));
            tiles[3071] = new Tile();
            tiles[3071].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3071.png")));
            tiles[3072] = new Tile();
            tiles[3072].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3072.png")));
            tiles[3073] = new Tile();
            tiles[3073].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3073.png")));
            tiles[3074] = new Tile();
            tiles[3074].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3074.png")));
            tiles[3075] = new Tile();
            tiles[3075].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3075.png")));
            tiles[3076] = new Tile();
            tiles[3076].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3076.png")));
            tiles[3077] = new Tile();
            tiles[3077].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3077.png")));
            tiles[3078] = new Tile();
            tiles[3078].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3078.png")));
            tiles[3079] = new Tile();
            tiles[3079].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3079.png")));
            tiles[3080] = new Tile();
            tiles[3080].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3080.png")));
            tiles[3149] = new Tile();
            tiles[3149].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3149.png")));
            tiles[3150] = new Tile();
            tiles[3150].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3150.png")));
            tiles[3151] = new Tile();
            tiles[3151].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3151.png")));
            tiles[3152] = new Tile();
            tiles[3152].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3152.png")));
            tiles[3153] = new Tile();
            tiles[3153].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3153.png")));
            tiles[3154] = new Tile();
            tiles[3154].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3154.png")));
            tiles[3155] = new Tile();
            tiles[3155].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3155.png")));
            tiles[3156] = new Tile();
            tiles[3156].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3156.png")));
            tiles[3157] = new Tile();
            tiles[3157].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3157.png")));
            tiles[3158] = new Tile();
            tiles[3158].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3158.png")));
            tiles[3159] = new Tile();
            tiles[3159].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3159.png")));
            tiles[3160] = new Tile();
            tiles[3160].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3160.png")));
            tiles[3161] = new Tile();
            tiles[3161].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3161.png")));
            tiles[3162] = new Tile();
            tiles[3162].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3162.png")));
            tiles[3163] = new Tile();
            tiles[3163].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3163.png")));
            tiles[3164] = new Tile();
            tiles[3164].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3164.png")));
            tiles[3165] = new Tile();
            tiles[3165].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3165.png")));
            tiles[3234] = new Tile();
            tiles[3234].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3234.png")));
            tiles[3235] = new Tile();
            tiles[3235].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3235.png")));
            tiles[3236] = new Tile();
            tiles[3236].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3236.png")));
            tiles[3237] = new Tile();
            tiles[3237].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3237.png")));
            tiles[3238] = new Tile();
            tiles[3238].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3238.png")));
            tiles[3239] = new Tile();
            tiles[3239].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3239.png")));
            tiles[3240] = new Tile();
            tiles[3240].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3240.png")));
            tiles[3241] = new Tile();
            tiles[3241].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3241.png")));
            tiles[3242] = new Tile();
            tiles[3242].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3242.png")));
            tiles[3243] = new Tile();
            tiles[3243].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3243.png")));
            tiles[3244] = new Tile();
            tiles[3244].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3244.png")));
            tiles[3245] = new Tile();
            tiles[3245].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3245.png")));
            tiles[3246] = new Tile();
            tiles[3246].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3246.png")));
            tiles[3247] = new Tile();
            tiles[3247].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3247.png")));
            tiles[3248] = new Tile();
            tiles[3248].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3248.png")));
            tiles[3249] = new Tile();
            tiles[3249].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3249.png")));
            tiles[3250] = new Tile();
            tiles[3250].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3250.png")));
            tiles[3319] = new Tile();
            tiles[3319].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3319.png")));
            tiles[3320] = new Tile();
            tiles[3320].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3320.png")));
            tiles[3321] = new Tile();
            tiles[3321].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3321.png")));
            tiles[3322] = new Tile();
            tiles[3322].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3322.png")));
            tiles[3323] = new Tile();
            tiles[3323].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3323.png")));
            tiles[3324] = new Tile();
            tiles[3324].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3324.png")));
            tiles[3325] = new Tile();
            tiles[3325].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3325.png")));
            tiles[3326] = new Tile();
            tiles[3326].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3326.png")));
            tiles[3327] = new Tile();
            tiles[3327].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3327.png")));
            tiles[3328] = new Tile();
            tiles[3328].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3328.png")));
            tiles[3329] = new Tile();
            tiles[3329].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3329.png")));
            tiles[3330] = new Tile();
            tiles[3330].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3330.png")));
            tiles[3331] = new Tile();
            tiles[3331].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3331.png")));
            tiles[3332] = new Tile();
            tiles[3332].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3332.png")));
            tiles[3333] = new Tile();
            tiles[3333].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3333.png")));
            tiles[3334] = new Tile();
            tiles[3334].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3334.png")));
            tiles[3335] = new Tile();
            tiles[3335].image = ImageIO.read(Objects.requireNonNull(getClass().getResource("/tiles/tile_3335.png")));
        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

    // CAMERA
    public void draw(Graphics2D graphics2D) {
        int worldColum = 0;
        int worldRow = 0;

        while (worldColum < gamePanel.getMAX_WORLD_COLUMN() && worldRow < gamePanel.getMAX_WORLD_ROW()) {
            int tileNumber = mapTileNumber[worldColum][worldRow];

            int worldX = worldColum * gamePanel.getTILE_SIZE();
            int worldY = worldRow * gamePanel.getTILE_SIZE();
            int screenX = worldX - gamePanel.getPlayer().getWorldX() + gamePanel.getPlayer().getSCREEN_X();
            int screenY = worldY - gamePanel.getPlayer().getWorldY() + gamePanel.getPlayer().getSCREEN_Y();

            // Boundary (so not all map is loaded because it's not needed => save memory
            if (worldX + gamePanel.getTILE_SIZE() > gamePanel.getPlayer().getWorldX() - gamePanel.getPlayer().getSCREEN_X()
                    && worldX - gamePanel.getTILE_SIZE() < gamePanel.getPlayer().getWorldX() + gamePanel.getPlayer().getSCREEN_X()
                    && worldY + gamePanel.getTILE_SIZE() > gamePanel.getPlayer().getWorldY() - gamePanel.getPlayer().getSCREEN_Y()
                    && worldY - gamePanel.getTILE_SIZE() < gamePanel.getPlayer().getWorldY() + gamePanel.getPlayer().getSCREEN_Y()
            ) {
                graphics2D.drawImage(tiles[tileNumber].image, screenX, screenY, gamePanel.getTILE_SIZE(), gamePanel.getTILE_SIZE(), null);
            }
            worldColum++;

            if (worldColum == gamePanel.getMAX_WORLD_COLUMN()) {
                worldColum = 0;
                worldRow++;
            }
        }
    }

    public void loadMap(String filePath) {
        try {
            InputStream inputStream = getClass().getResourceAsStream(filePath);
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(inputStream));

            int column = 0;
            int row = 0;

            while (column < gamePanel.getMAX_WORLD_COLUMN() && row < gamePanel.getMAX_WORLD_ROW()) {
                String line = bufferedReader.readLine();

                while (column < gamePanel.getMAX_WORLD_COLUMN()) {
                    String[] numbers = line.split(" ");
                    int number = Integer.parseInt(numbers[column]);

                    mapTileNumber[column][row] = number;
                    column++;
                }
                if (column == gamePanel.getMAX_WORLD_COLUMN()) {
                    column = 0;
                    row++;
                }
            }

            bufferedReader.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
